version: '3.8'
services:
  web:
    image: allower99/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: allower99/backend:latest
    environment:
      - VARS=HERE
