name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Docker build and push
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push backend
      run: |
        docker build -t allower99/backend:latest ./backend
        docker push allower99/backend:latest

    - name: Build and push nginx
      run: |
        docker build -t allower99/nginx:latest ./nginx
        docker push allower99/nginx:latest

    # SSH deployment
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}

    - name: Deploy to production
      run: |
        ssh -tt -o StrictHostKeyChecking=no root@${{ secrets.PROD_HOST }} << 'EOF'
        docker pull allower99/backend:latest
        docker pull allower99/nginx:latest
        cd /opt/project-root
        docker-compose down
        docker-compose up -d
        EOF
